package nijakow.four.smalltalk.parser;

public enum TokenType {
    EOF, ERROR, COMMENT, DOCUMENTAR, PRIMITIVE,
    IDENTIFIER, SYMBOL, INTEGER, CHARACTER, STRING,
    LPAREN, RPAREN,
    LBRACK, RBRACK,
    BAR, CARET,
    DOT, COMMA, COLON, SEMICOLON,
    ASSIGN,
    SELF, SUPER, TRUE, FALSE, NIL, THISCONTEXT
}
